[project]
name = 'Weather-Prediction-Market'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.historical-analysis]
path = 'contracts/historical-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.weather-data]
path = 'contracts/weather-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
